application: friendly-aurora-855
version: alpha-001
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/data-form/2017
  static_files: data-form.html
  upload: data-form.html
  secure: always

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/data-form/2016
  static_files: 2016/data-form.html
  upload: 2016/data-form.html
  secure: always

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/review/2017
  static_files: review.html
  upload: review.html
  secure: always

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/review/2016
  static_files: 2016/review.html
  upload: 2016/review.html
  secure: always

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/report/2017
  static_files: report.html
  upload: report.html
  secure: always

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/report/2016
  static_files: 2016/report.html
  upload: 2016/report.html
  secure: always

- url: /metropolis/[A-Z]+/admin
  static_files: admin.html
  upload: admin.html
  secure: always

- url: /metropolis/[A-Z]+/summary
  static_files: summary.html
  upload: summary.html
  secure: always

- url: /metropolis/[A-Z]+/stewardship
  static_files: stewardship.html
  upload: stewardship.html
  secure: always

- url: /(.*\.(gif|png|jpg|html|css|js))$
  static_files: \1
  upload: .*\.(gif|png|jpg|html|css|js)$
  secure: always

- url: /2016/(.*\.(gif|png|jpg|html|css|js))$
  static_files: \1
  upload: 2016/.*\.(gif|png|jpg|html|css|js)$
  secure: always
