application: friendly-aurora-855
version: alpha-001
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /parish/2016/(.*\.(gif|png|jpg|html|css))$
  static_files: \1
  upload: .*\.(gif|png|jpg|html|css)$

- url: /(.*\.(gif|png|jpg|html|css))$
  static_files: \1
  upload: .*\.(gif|png|jpg|html|css)$

