application: friendly-aurora-855
version: alpha-001
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /metropolis/[A-Z]+/parish/[-a-z0-9]*/data-form/20[0-9][0-9]
  static_files: data-form.html
  upload: data-form.html
  secure: always

- url: /metropolis/[A-Z]+/admin
  static_files: admin.html
  upload: admin.html
  secure: always

- url: /(.*\.(gif|png|jpg|html|css|js))$
  static_files: \1
  upload: .*\.(gif|png|jpg|html|css|js)$
  secure: always

